test: pipeline CI error controlado

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -31,13 +31,13 @@ jobs:
       - name: Mostrar versión de Git
         run: git --version
         
-      - name: Provocar error controlado
-        run: |
-          echo "================================"
-          echo "      ERROR CONTROLADO"
-          echo "================================"
-          echo "Este error es intencional para probar el pipeline."
-          exit 1
+      #- name: Provocar error controlado
+      #  run: |
+      #    echo "================================"
+      #    echo "      ERROR CONTROLADO"
+      #    echo "================================"
+      #    echo "Este error es intencional para probar el pipeline."
+      #    exit 1
 
       - name: Finalizar pipeline
         run: echo "Pipeline ejecutado correctamente."
